name: Push content to the user's Github pages repository

on:
  push

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 12.x ]
      steps:
      - name: Make out folder
        run: mkdir out
      - name: Clone master branch
        run: git clone "https://${{secrets.ACTIONS_DEPLOY_KEY}}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" --branch master --single-branch ./out
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Set git config and add changes
        run: |
          git config user.email "${{GITHUB_ACTOR}}@https://users.noreply.github.com"
          git config user.name "${{GITHUB_ACTOR}}"
          git add --all
        working-directory: ./out
      - name: Push
        run: |
          COMMIT_MESSAGE="Update pages on $(data + '%Y-%m-%d %H:%M:%S')"
          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          git commit -m "${COMMIT_MESSAGE}"
          git push https://{{secrets.ACTIONS_DEPLOY_KEY}}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git master
